"""Prompts package."""

from .system_prompts import (
    MASTER_AGENT_PROMPT,
    MASTER_AGENT_PROMPT_BASE,
    SEARCH_AGENT_PROMPT,
    DATA_INSIGHT_AGENT_PROMPT,
    METADATA_AGENT_PROMPT,
    QUERY_PLANNING_PROMPT,
    ANSWER_SYNTHESIS_PROMPT,
    CONVERSATION_CONTEXT_PROMPT
)

__all__ = [
    'MASTER_AGENT_PROMPT',
    'MASTER_AGENT_PROMPT_BASE',
    'SEARCH_AGENT_PROMPT',
    'DATA_INSIGHT_AGENT_PROMPT',
    'METADATA_AGENT_PROMPT',
    'QUERY_PLANNING_PROMPT',
    'ANSWER_SYNTHESIS_PROMPT',
    'CONVERSATION_CONTEXT_PROMPT'
]
